config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#index'

  resources :qa_threads, path: 'qa' do
    post 'confirm', on: :collection
  end
  resources :qa_replies
  resources :simulations, path: 'simulate', only: %i(create) do
    get 'input', on: :collection
    get 'result/:uuid' => 'simulations#result', on: :collection, as: 'result'
  end

  namespace :admin do
    resources :opinions, only: %i(index)
  end

  namespace :private do
    namespace :api do
      namespace :v1 do
        resources :opinions do
          post "create"
        end
      end
    end
  end

  get '/404' => 'errors#render_404'
  get '/500' => 'errors#render_500'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  scope :new_order, -> { order('id desc') }

  enum carrier: {
    other: 0,
    docomo: 1,
    au: 2,
    softbank: 3,
  }

  def self.latest
    order(:id).last
  end
end

app/models/maker.rb
class Maker < ApplicationRecord
  has_many :terminals
end

app/models/opinion.rb
class Opinion < ApplicationRecord

end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :provider
  belongs_to :parent, class_name: 'Plan', foreign_key: :parent_id
  has_many :related_plans, class_name: 'Plan', foreign_key: :parent_id

  t = arel_table
  scope :data,  ->(num) { where(data_num: num) }
  scope :sms,   ->(num) { where(sms_num: num) }
  scope :voice, ->(num) { where(voice_num: num) }
  scope :capacity_over, ->(capacity) {
    where(t[:capacity].gteq(capacity)).or(where(capacity: nil))
  }
end

app/models/provider.rb
class Provider < ApplicationRecord
  has_many :plans
end

app/models/qa_reply.rb
class QaReply < ApplicationRecord
  belongs_to :user
  belongs_to :qa_thread
  has_many :replies, class_name: 'QaReply', foreign_key: :qa_reply_id

  DIRECTLY_BELOW = 0
  scope :directly_below, -> { where(qa_reply_id: DIRECTLY_BELOW) }
end

app/models/qa_thread.rb
class QaThread < ApplicationRecord
  belongs_to :user
  has_one :label, class_name: 'ThreadLabel', foreign_key: :qa_thread_id
  has_one :category, class_name: 'ThreadCategory', foreign_key: :qa_thread_id
  has_many :tags, class_name: 'ThreadTag', foreign_key: :qa_thread_id
  has_many :replies, class_name: 'QaReply', foreign_key: :qa_thread_id
end

app/models/simulation.rb
class Simulation < ApplicationRecord
  has_many :simulation_results
  has_many :plans, through: :simulation_results
  belongs_to :terminal

  def simulate!
    self.plans = Plan.public_send(simulation_carrier)
                     .public_send(simulation_type, 1)
                     .capacity_over(capacity).order(:price).limit(10)
    save!
  end

  private

  def simulation_carrier
    return carrier if terminal.blank?
    terminal.available_carrier
  end

  def simulation_type
    case
    when voice? then 'voice'
    when sms? then 'sms'
    else 'data'
    end
  end
end

app/models/simulation_result.rb
class SimulationResult < ApplicationRecord
  belongs_to :simulation
  belongs_to :plan
end

app/models/terminal.rb
class Terminal < ApplicationRecord
  belongs_to :maker
  has_many :simulation

  def available_carrier
    case
    when au? && band18_26? && band1?
      'au'
    when docomo? && band1? && band19?
      'docomo'
    else
      'other'
    end
  end
end

app/models/thread_category.rb
class ThreadCategory < ApplicationRecord
  belongs_to :qa_thread
end

app/models/thread_label.rb
class ThreadLabel < ApplicationRecord
  belongs_to :qa_thread
end

app/models/thread_tag.rb
class ThreadTag < ApplicationRecord
  belongs_to :qa_thread
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # :confirmable, :lockable, :timeoutable
  has_many :qa_threads
  has_many :qa_replies

  validates :password, length: { in: Devise.password_length }
end

app/controllers/admin/opinions_controller.rb
class Admin::OpinionsController < ApplicationController
  def index
    @opinions = Opinion.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(_resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:email, :password, :nickname)
    end
    devise_parameter_sanitizer.permit(:account_update) do |user_params|
      user_params.permit(:email, :password, :nickname, :password_confirmation, :current_password)
    end
  end

  private

  def clear_session_errors
    session[:errors] = []
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ActionController::Base
  layout 'application'

  rescue_from StandardError, with: :render_500
  rescue_from ActionController::RoutingError, with: :render_404
  rescue_from ActiveRecord::RecordNotFound, with: :render_404

  %w(404 500).each do |status_code|
    define_method("render_#{status_code}") do |exception = nil|
      logger.info "Rendering #{status_code} with exception: #{exception.message}" if exception
      render(
        file: Rails.root.join('public', "#{status_code}.html"),
        status: status_code.to_i, layout: false, content_type: 'text/html'
      )
    end
  end

  def show
    raise env['action_dispatch.exception']
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index; end

  def show; end
end

app/controllers/qa_replies_controller.rb
class QaRepliesController < ApplicationController
  def create
    qa_reply = current_user.qa_replies.new(qa_reply_params)
    qa_reply.save

    redirect_to qa_thread_path(qa_reply.qa_thread)
  end

  private

  def qa_reply_params
    params.require(:qa_reply).permit(:qa_thread_id, :qa_reply_id, :content)
  end
end

app/controllers/qa_threads_controller.rb
class QaThreadsController < ApplicationController
  def new
    @qa_thread = session[:qa_thread] ? QaThread.new(session[:qa_thread]) : QaThread.new
  end

  def confirm
    @qa_thread = QaThread.new(qa_thread_params)
    # TODO: validation check
    session[:qa_thread] = @qa_thread
  end

  def create
    qa_thread = current_user.qa_threads.new(session[:qa_thread])
    qa_thread.save
    # TODO: Thanks modal
    redirect_to qa_thread_path(qa_thread)
  end

  def show
    @qa_thread = QaThread.find(params[:id])
    @qa_replies = @qa_thread.replies.directly_below.eager_load(:replies)
    @qa_reply = @qa_thread.replies.new
  end

  private

  def qa_thread_params
    params.require(:qa_thread).permit(:title, :carrier, :terminal, :content)
  end
end

app/controllers/simulations_controller.rb
class SimulationsController < ApplicationController
  def input
    @simulation = Simulation.new
  end

  def create
    @simulation = Simulation.new(simulation_params)
    @simulation.simulate!

    redirect_to result_simulations_path(@simulation)
  end

  def result
    @simulation = Simulation.find(params[:uuid])
  end

  private

  def simulation_params
    params.require(:simulation).permit(:carrier, :terminal_id, :capacity, :voice, :sms, :speed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/qa_threads/confirm.html.slim
.org__attention-eyecatch
  .mol__eyecatch
    h2 投稿前にご確認ください
    p.description
      | 下記の内容で投稿します。よろしいですか？
.org__breadcrumb
  .a__breadcrumb
    ol itemtype="http://schema.org/BreadcrumbList"
      li itemprop="itemListElement" itemtype="http://schema.org/ListItem"
        a href="/" title="トップ" itemprop="url"
          span itemprop="title"
            | トップ
      li itemprop="itemListElement"
        .a__breadcrumb_now itemprop="name" 質問を作成する
.org__content.mm--confirm
  = form_for(@qa_thread) do |f|
    .qa_thread-main
      .mol__form
        = label :qa_thread, :title, 'タイトル', class:"a__plate a__required"
        .a__confirm-content
          = @qa_thread.title
      .mol__form
        = label :qa_thread, :carrier, 'キャリア', class:"a__plate"
        .a__confirm-content
          = @qa_thread.carrier
      .mol__form
        = label :qa_thread, :terminal, '端末', class:"a__plate"
        .a__confirm-content
          = @qa_thread.terminal
      .mol__form
        = label :qa_thread, :content, '本文', class:"a__plate a__required"
        .a__confirm-content
          = @qa_thread.content
      .mol__form.mm__back-next
        = link_to '編集し直す', new_qa_thread_path, class:'a__button-basic'
        .mol__button
          = f.submit '投稿を完了する', class: 'a__button'
          span.a__caution 投稿した内容は1時間の間編集することができます

app/views/qa_threads/new.html.slim
.org__attention-eyecatch
  .mol__eyecatch
    h2.caption
      | 掲示板に質問してみよう！
    p
      | 自分にとってぴったりの格安SIMはなに？みんなどんな工夫をして使っている？<br>
      | 格安スマホに切り替えた決めては何だった？
      | スマホの気になることをみんなに聞いてみよう。
    div
      = link_to '投稿に関する質問はこちら', '/'
.org__breadcrumb
  .a__breadcrumb
    ol itemtype="http://schema.org/BreadcrumbList"
      li itemprop="itemListElement" itemtype="http://schema.org/ListItem"
        a href="/" title="トップ" itemprop="url"
          span itemprop="title"
            | トップ
      li itemprop="itemListElement"
        .a__breadcrumb_now itemprop="name" 質問を作成する
.org__content.mm--new
  // 今は使わない
    .mol__eyecatch
      h2 掲示板に質問してみよう！
      p.description
        | スマホ・格安SIMの疑問をみんなに聞いてみよう
      div
        = link_to '投稿に関する質問はこちら', '/'
  .mol__qa-content
    = form_for(@qa_thread, url: { action: :confirm }) do |f|
      .mol__qa-thread-main
        .mol__form
          = label :qa_thread, :title, '質問のタイトル', class: 'a__plate a__required'
          = f.text_field :title, placeholder:'質問のタイトルをお書きください', class: 'a__plate'
        .mol__form
          = label :qa_thread, :carrier, 'ご自身が使っている通信キャリア', class: 'a__plate'
          span.a__select
            = f.select :carrier, QaThread.carriers_i18n.invert, {}, {class:'a__plate'}
            // デフォルトの項目は "書きよりお選びください"
        .mol__form
          = label :qa_thread, :terminal, '端末', class: 'a__plate'
          = f.text_field :terminal, { class: 'a__plate' }
        // 質問が集まってきたらラベル項目を設ける
        //  div
        //    = label :qa_thread, :terminal, 'ラベル'
        //    = f.text_field :terminal
        .mol__form
          = label :qa_thread, :content, '本文', class: 'a__plate a__required'
          = f.text_area :content, size: "60x10", placeholder:'わからないこと、解決したいことをお書きください', class:'a__plate'
        .mol__button
          = f.submit '次に進む', class: 'a__button'
          span.a__caution 確認画面に移動します
    .org__qa-thread-sidebar
      .mol__qa-pannel
        h2 よくある質問
        .mol__wrapper
          a.mol__qa-tile
            .mol__caption
              p.caption
                | 現在ソフトバンクのiPhone6を使っているのですが、オススメの格安 SIM があれば教えてください。
            .mol__data
              .a__item-data
                span.caption 回答者
                .a__data 1
              .a__item-data
                span.caption 閲覧数
                .a__data 76
              .a__item-data
                span.caption 気になる
                .a__data 10
          a.mol__qa-tile
            .mol__caption
              p.caption
                | 現在ソフトバンクのiPhone6を使っているのですが、オススメの格安 SIM があれば教えてください。
            .mol__data
              .a__item-data
                span.caption 回答者
                .a__data 1
              .a__item-data
                span.caption 閲覧数
                .a__data 76
              .a__item-data
                span.caption 気になる
                .a__data 10
          a.mol__qa-tile
            .mol__caption
              p.caption
                | 現在ソフトバンクのiPhone6を使っているのですが、オススメの格安 SIM があれば教えてください。
            .mol__data
              .a__item-data
                span.caption 回答者
                .a__data 1
              .a__item-data
                span.caption 閲覧数
                .a__data 76
              .a__item-data
                span.caption 気になる
                .a__data 10
        a.a__read-more href='/' title='続きを見る...' 続きを見る...

app/views/qa_threads/show.html.slim
.clearfix
  .qa_thread-main
    div
      = @qa_thread.title
    div
      = @qa_thread.content
  .qa_thread-sidebar
    div
      | このカテゴリの質問
    div
      | あいうえお
div
  = link_to '回答する', root_path
  div
    = form_for(@qa_reply) do |f|
      = f.hidden_field :qa_thread_id, value: @qa_thread.id
      = f.text_area :content
      = f.submit '回答する'
div
  - @qa_replies.each do |reply|
    div
      = reply.content
    - reply.replies.each do |child_reply|
      div
        = child_reply.content
    = form_for(reply.replies.new) do |rf|
      = rf.hidden_field :qa_thread_id, value: @qa_thread.id
      = rf.hidden_field :qa_reply_id, value: reply.id
      = rf.text_area :content
      = rf.submit '返信する'

app/views/simulations/input.html.slim
= form_for @simulation do |f|
  | 通信回線
  = f.select :carrier, Simulation.carriers.map { |k, _| [k, k] }
  br
  | お使いの端末
  = f.select :terminal_id, [['指定しない', nil]] + Terminal.pluck(:name, :id)
  br
  | 通信量
  = f.text_field :capacity
  | GB
  br
  | 音声通話
  = f.radio_button 'voice', '1', checked: true
  | 利用する
  = f.radio_button 'voice', '2'
  | 利用しない
  br
  | SMS
  = f.radio_button 'sms', '1', checked: true
  | 利用する
  = f.radio_button 'sms', '2'
  | 利用しない
  br
  | 通信速度
  = f.text_field 'speed'
  | Mbps
  br
  = f.submit '診断する'

app/views/simulations/result.html.slim
- @simulation.plans.eager_load(:provider).order(:price).each do |plan|
  = "プラン名: #{plan.name}, 事業者名: #{plan.provider.name}, 価格: #{plan.price}円"
  br