config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#index'

  resources :qa_threads, path: 'qa' do
    post 'confirm', on: :collection
  end
  resources :qa_replies
  resources :simulations, path: 'simulate', only: %i(create) do
    get 'input', on: :collection
    get 'result/:uuid' => 'simulations#result', on: :collection, as: 'result'
  end

  namespace :admin do
    resources :opinions, only: %i(index)
  end

  namespace :private do
    namespace :api do
      namespace :v1 do
        resources :opinions do
          post "create"
        end
      end
    end
  end

  get '/404' => 'errors#render_404'
  get '/500' => 'errors#render_500'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  scope :new_order, -> { order('id desc') }

  enum carrier: {
    other: 0,
    docomo: 1,
    au: 2,
    softbank: 3,
  }

  def self.latest
    order(:id).last
  end
end

app/models/maker.rb
class Maker < ApplicationRecord
  has_many :terminals
end

app/models/opinion.rb
class Opinion < ApplicationRecord

end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :provider
  belongs_to :parent, class_name: 'Plan', foreign_key: :parent_id
  has_many :related_plans, class_name: 'Plan', foreign_key: :parent_id

  t = arel_table
  scope :data,  ->(num) { where(data_num: num) }
  scope :sms,   ->(num) { where(sms_num: num) }
  scope :voice, ->(num) { where(voice_num: num) }
  scope :capacity_over, ->(capacity) {
    where(t[:capacity].gteq(capacity)).or(where(capacity: nil))
  }
end

app/models/provider.rb
class Provider < ApplicationRecord
  has_many :plans
end

app/models/qa_reply.rb
class QaReply < ApplicationRecord
  belongs_to :user
  belongs_to :qa_thread
  has_many :replies, class_name: 'QaReply', foreign_key: :qa_reply_id

  DIRECTLY_BELOW = 0
  scope :directly_below, -> { where(qa_reply_id: DIRECTLY_BELOW) }
end

app/models/qa_thread.rb
class QaThread < ApplicationRecord
  belongs_to :user
  has_one :label, class_name: 'ThreadLabel', foreign_key: :qa_thread_id
  has_one :category, class_name: 'ThreadCategory', foreign_key: :qa_thread_id
  has_many :tags, class_name: 'ThreadTag', foreign_key: :qa_thread_id
  has_many :replies, class_name: 'QaReply', foreign_key: :qa_thread_id
end

app/models/simulation.rb
class Simulation < ApplicationRecord
  has_many :simulation_results
  has_many :plans, through: :simulation_results
  belongs_to :terminal

  def simulate!
    self.plans = Plan.public_send(simulation_carrier)
                     .public_send(simulation_type, 1)
                     .capacity_over(capacity).order(:price).limit(10)
    save!
  end

  private

  def simulation_carrier
    return carrier if terminal.blank?
    terminal.available_carrier
  end

  def simulation_type
    case
    when voice? then 'voice'
    when sms? then 'sms'
    else 'data'
    end
  end
end

app/models/simulation_result.rb
class SimulationResult < ApplicationRecord
  belongs_to :simulation
  belongs_to :plan
end

app/models/terminal.rb
class Terminal < ApplicationRecord
  belongs_to :maker
  has_many :simulation

  def available_carrier
    case
    when au? && band18_26? && band1?
      'au'
    when docomo? && band1? && band19?
      'docomo'
    else
      'other'
    end
  end
end

app/models/thread_category.rb
class ThreadCategory < ApplicationRecord
  belongs_to :qa_thread
end

app/models/thread_label.rb
class ThreadLabel < ApplicationRecord
  belongs_to :qa_thread
end

app/models/thread_tag.rb
class ThreadTag < ApplicationRecord
  belongs_to :qa_thread
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # :confirmable, :lockable, :timeoutable
  has_many :qa_threads
  has_many :qa_replies

  validates :password, length: { in: Devise.password_length }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(_resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:email, :password, :nickname)
    end
    devise_parameter_sanitizer.permit(:account_update) do |user_params|
      user_params.permit(:email, :password, :nickname, :password_confirmation, :current_password)
    end
  end

  private

  def clear_session_errors
    session[:errors] = []
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ActionController::Base
  layout 'application'

  rescue_from StandardError, with: :render_500
  rescue_from ActionController::RoutingError, with: :render_404
  rescue_from ActiveRecord::RecordNotFound, with: :render_404

  %w(404 500).each do |status_code|
    define_method("render_#{status_code}") do |exception = nil|
      logger.info "Rendering #{status_code} with exception: #{exception.message}" if exception
      render(
        file: Rails.root.join('public', "#{status_code}.html"),
        status: status_code.to_i, layout: false, content_type: 'text/html'
      )
    end
  end

  def show
    raise env['action_dispatch.exception']
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index; end

  def show; end
end

app/controllers/qa_replies_controller.rb
class QaRepliesController < ApplicationController
  def create
    qa_reply = current_user.qa_replies.new(qa_reply_params)
    qa_reply.save

    redirect_to qa_thread_path(qa_reply.qa_thread)
  end

  private

  def qa_reply_params
    params.require(:qa_reply).permit(:qa_thread_id, :qa_reply_id, :content)
  end
end

app/controllers/qa_threads_controller.rb
class QaThreadsController < ApplicationController
  def new
    @qa_thread = session[:qa_thread] ? QaThread.new(session[:qa_thread]) : QaThread.new
  end

  def confirm
    @qa_thread = QaThread.new(qa_thread_params)
    # TODO: validation check
    session[:qa_thread] = @qa_thread
  end

  def create
    qa_thread = current_user.qa_threads.new(session[:qa_thread])
    qa_thread.save
    # TODO: Thanks modal
    redirect_to qa_thread_path(qa_thread)
  end

  def show
    @qa_thread = QaThread.find(params[:id])
    @qa_replies = @qa_thread.replies.directly_below.eager_load(:replies)
    @qa_reply = @qa_thread.replies.new
  end

  private

  def qa_thread_params
    params.require(:qa_thread).permit(:title, :carrier, :terminal, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_error.html.slim
- if session[:errors].present? || flash[:error].present?
  .errors-wrap
    .errors
      - session[:errors].each do |error_message|
        .validation_error
          = error_message
      - if flash[:error].present?
        .validation_error
          = flash[:error]

app/views/layouts/_footer.html.slim
.org__footer
  .org__inner-footer
    .mol__content
      .mol__wraper
        .a__caption Q&A
        a.span 格安 SIM の選び方 Q＆A
        a.span 切り替え後のセットアップ Q＆A
      .mol__wraper
        .a__caption 格安SIM切り替えレビュー
        a.span 乗り換え体験談
      .mol__wraper
        .a__caption その他
        a.span 初めての方へ
        a.span マイページ
    .mol__opinion
      .a__inner
        span.caption 本サービスへのご意見<br>ご要望をお聞かせください
        form action="footer-opinion" method="post" class="a__plate footer-opinion"
        #vue-footer-opinion
        = javascript_include_tag 'footerOpinion'
  .a__copyright
    | Copyright © 2017 lassi All Rights Reserved.&nbsp;
    = link_to 'GitHub', 'https://github.com/yuyasat/lassi'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Simnity | SIMのお悩みをみんなで解決するQ&Aサイト
      <%# TODO ogp、description等の設定もする #>
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = Gon::Base.render_data({})
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    .org__header
      .mol__global-header
        a.a__logo-link href='/' title='トップ'
          .a__logo
        nav.header-nav
          ul.nav-lists
            li コミュニティ
            / 一旦コメントアウト
            / nav
              ul
                li
                  / url が決まっていないので一旦 root_path を入れてます
                  = link_to '格安SIMの選び方', root_path
                li
                  / url が決まっていないので一旦 root_path を入れてます
                  = link_to '事業者別Q&A', root_path
                li
                  / url が決まっていないので一旦 root_path を入れてます
                  = link_to '切り替え後のセットアップ', root_path

            - if user_signed_in?
              li
                div
                  = link_to 'プロフィール変更', edit_user_registration_path
              li
                = link_to 'ログアウト', destroy_user_session_path, method: :delete
            - else
              li
                = link_to 'サインアップ', new_user_registration_path
              li
                = link_to 'ログイン', new_user_session_path
    - if notice.present?
      p.notice
        = notice
    - if alert.present?
      p.alert
        = alert
    .container
      = yield
    = render 'layouts/footer'

app/views/pages/index.html.slim
.org__global-eyecatch
  .mol__description
    h1.caption
      | 格安SIM、どれに変えていいかわからない？
    p
      | SIMのお悩みは詳しい人に聞いてみよう！<br>
      | Simnity なら、SIMに詳しいスペシャリストがたくさんいます。<br>
      | 有益なアドバイスをもらってあなたにぴったりの格安SIMに変えましょう！
    =link_to '早速診断してみる', input_simulations_path, title: '早速診断してみる', class: 'a__button'
.org__content
  .org__inner-content
    .org__main
      .mol__qa-pannel
        h2 格安SIMの選び方 Q&A
        .mol__wrapper
          a.mol__qa-tile
            .mol__caption
              p.caption
                | 現在ソフトバンクのiPhone6を使っているのですが、オススメの格安 SIM があれば教えてください。
            .mol__data
              .a__item-data
                span.caption 回答者
                .a__data 1
              .a__item-data
                span.caption 閲覧数
                .a__data 76
              .a__item-data
                span.caption 気になる
                .a__data 10
          a.mol__qa-tile
            .mol__caption
              p.caption
                | 現在ソフトバンクのiPhone6を使っているのですが、オススメの格安 SIM があれば教えてください。
            .mol__data
              .a__item-data
                span.caption 回答者
                .a__data 1
              .a__item-data
                span.caption 閲覧数
                .a__data 76
              .a__item-data
                span.caption 気になる
                .a__data 10
          a.mol__qa-tile
            .mol__caption
              p.caption
                | 現在ソフトバンクのiPhone6を使っているのですが、オススメの格安 SIM があれば教えてください。
            .mol__data
              .a__item-data
                span.caption 回答者
                .a__data 1
              .a__item-data
                span.caption 閲覧数
                .a__data 76
              .a__item-data
                span.caption 気になる
                .a__data 10
        a.a__read-more href='/' title='続きを見る...' 続きを見る...
      .mol__qa-pannel
        h2 格安SIMの選び方 Q&A
        .mol__wrapper
          a.mol__qa-tile
            .mol__caption
              p.caption
                | 現在ソフトバンクのiPhone6を使っているのですが、オススメの格安 SIM があれば教えてください。
            .mol__data
              .a__item-data
                span.caption 回答者
                .a__data 1
              .a__item-data
                span.caption 閲覧数
                .a__data 76
              .a__item-data
                span.caption 気になる
                .a__data 10
          a.mol__qa-tile
            .mol__caption
              p.caption
                | 現在ソフトバンクのiPhone6を使っているのですが、オススメの格安 SIM があれば教えてください。
            .mol__data
              .a__item-data
                span.caption 回答者
                .a__data 1
              .a__item-data
                span.caption 閲覧数
                .a__data 76
              .a__item-data
                span.caption 気になる
                .a__data 10
          a.mol__qa-tile
            .mol__caption
              p.caption
                | 現在ソフトバンクのiPhone6を使っているのですが、オススメの格安 SIM があれば教えてください。
            .mol__data
              .a__item-data
                span.caption 回答者
                .a__data 1
              .a__item-data
                span.caption 閲覧数
                .a__data 76
              .a__item-data
                span.caption 気になる
                .a__data 10
        a.a__read-more href='/' title='続きを見る...' 続きを見る...
    .org__sidebar
     .banner
      img src=image_url('banner1.png')